name: repair_cms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.9.1
  feather_icons: ^1.2.0
  solar_icons: ^0.0.5
  lottie: ^3.3.1
  oktoast: ^3.4.0

  # State Management & Routing
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.2.1
  get_it: ^8.2.0

  # Networking
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  http_parser: ^4.1.2
  mime: ^2.0.0

  # Storage & Local Data
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5

  # Auth & Security
  local_auth: ^2.3.0
  local_auth_android: ^1.0.52
  local_auth_ios: ^1.1.7

  # Forms & Input
  pinput: ^5.0.2
  drop_down_search_field: ^1.2.2
  image_picker: ^1.2.0

  # Utilities
  intl: ^0.18.1
  syncfusion_flutter_datepicker: ^31.1.19
  file_picker: ^10.3.3
  modal_bottom_sheet: ^3.0.0
  uuid: ^4.5.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.4.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
          style: normal

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
